### PR TITLE
markdown-service: add support for ul/ol

### PR DESCRIPTION
**Pull request by knholland**
When content contains a ul or ol, a condition could exist that would
cause exposed HTML.

Fixes: CNNSP-337
Reviewed-By: Katie Owen katie.owen@turner.com

### CODE REVIEW

**Review by jamsyoung — CHANGES_REQUESTED** [review]
Needs to have conflicts resolved.

**Comment by knholland** [comment]
Updated to remove conflicts.

**Review by jamsyoung — APPROVED** [review]

**Comment by jamsyoung** [comment]
Conflicted again.

Is this needed with the changes coming in from #6 ?

**Comment by knholland** [comment]
Updated to remove conflicts.

**Review by jamsyoung — APPROVED** [review]

**Review by zoitec — APPROVED** [review]
Looks good.

**Pull request merged**
